---
- name: Configurar base de datos y usuarios
  hosts: dbservers
  become: true
  vars_files:
    - vault/secrets.yml
  roles:
    - mysql

- name: Configurar servidores web
  hosts: webservers
  become: true
  vars_files:
    - vault/secrets.yml
  roles:
    - apache
    - php
    - app

- name: Configurar balanceador de carga
  hosts: loadbalancers
  become: true
  vars:
    is_load_balancer: true
  roles:
    - nginx
    