---
- name: Instalar MySQL Server
  apt:
    name: 
      - mysql-server
      - python3-mysqldb
    state: present
    update_cache: yes

- name: Iniciar servicio MySQL
  service:
    name: mysql
    state: started
    enabled: true

- name: Configurar la contraseña de root de MySQL
  mysql_user:
    name: root
    password: "{{ vault_mysql_root_password }}"
    host: localhost
    login_user: root #Podemos poner otro usuario si lo deseamos
    login_password: "{{ vault_mysql_root_password }}"

- name: Crear base de datos
  mysql_db:
    name: "{{ mysql_database }}"
    state: present
    login_user: root #Podemos poner otro usuario si lo deseamos
    login_password: "{{ vault_mysql_root_password }}"

- name: Crear usuario de app wordpressdb
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ vault_mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    state: present
    login_user: root #Podemos poner otro usuario si lo deseamos
    login_password: "{{ vault_mysql_root_password }}"