#SPDX-License-Identifier: MIT-0
---
# tasks file for app
- name: Instalar WordPress
  apt:
    name: 
      - curl
      - tar
      - unzip
      - wget
    state: present
    update_cache: yes

- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: /var/www/html/wp-settings.php

- name: Configurar permisos de WordPress
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes

- name: Copiar archivo de configuración de WordPress
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: www-data
    group: www-data
    mode  : '0640'