---
- name: Configurar base de datos y usuarios
  hosts: dbservers
  become: true
  vars_files:
    - ../vault/secrets.yml
  roles:
    - role: mysql

- name: Configurar servidores web
  hosts: webservers
  become: true
  vars_files:
    - ../vault/secrets.yml
  roles:
    - role: apache
    - role: php
    - role: app

- name: Configurar balanceador de carga
  hosts: loadbalancers
  become: true
  vars:
    is_load_balancer: true
  roles:
    - role: nginx
    